{% set name = "pattern-causality" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/skstavroglou/pattern_causality_py/releases/download/v{{ version }}/pattern_causality-{{ version }}.tar.gz

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [win32 or py<38]
  features:
    - vc14  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - python
    - pip
    - numpy >=1.19.0
    - setuptools >=45
    - wheel
    - libomp  # [osx]
    - vs2017_win-64  # [win]
    - m2w64-toolchain  # [win]
  host:
    - python >=3.8
    - pip
    - numpy >=1.19.0
    - pandas >=1.0.0
    - setuptools >=45
    - wheel
    - vs2017_win-64  # [win]
  run:
    - python >=3.8
    - {{ pin_compatible('numpy', min_pin='x.x', max_pin='x.x') }}
    - pandas >=1.0.0
    - vs2017_runtime  # [win]

test:
  imports:
    - pattern_causality
    - pattern_causality.utils
  requires:
    - pytest >=6.0
    - pytest-cov >=2.0
  commands:
    - pip check
    - pytest tests/ -v

about:
  home: https://github.com/skstavroglou/pattern_causality_py
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Pattern Causality Algorithm in Python
  description: |
    A comprehensive Python library that implements the Pattern Causality algorithm 
    for analyzing causal relationships in time series data. This package provides 
    efficient tools for detecting and quantifying causality patterns between 
    multiple time series, with a particular focus on nonlinear complex systems.
  doc_url: https://github.com/skstavroglou/pattern_causality_py#readme
  dev_url: https://github.com/skstavroglou/pattern_causality_py

extra:
  recipe-maintainers:
    - huiw1128
  maintainers:
    - Hui Wang <huiw1128@gmail.com>
  authors:
    - Stavros Stavroglou <stavros.k.stavroglou@gmail.com>
    - Athanasios Pantelous <Athanasios.Pantelous@monash.edu>
    - Hui Wang <huiw1128@gmail.com> 